version: 2

sources:
  - name: estat
    description: "e-Stat APIから取得した統計データ（CSVファイル）"
    meta:
      external_location: "../data/{name}/{name}.csv"
    tables:
      - name: "0000010103"
        description: "社会・人口統計体系 - Ｃ 経済基盤（都道府県別）"
      - name: "0000010112"
        description: "社会・人口統計体系 - Ｌ 家計（都道府県別）"
      - name: "0002210008"
        description: "家計調査 - 貯蓄・負債（都市階級・地方・県庁所在市別）"
      - name: "0004026264"
        description: "人口推計 - 都道府県・男女別人口"
      - name: "0004032502"
        description: "商業動態統計調査 - コンビニエンスストア 都道府県別販売額等"
      - name: "0004032505"
        description: "商業動態統計調査 - 家電大型専門店 都道府県別販売額等"
      - name: "0004032508"
        description: "商業動態統計調査 - ドラッグストア 都道府県別販売額等"
      - name: "0004032511"
        description: "商業動態統計調査 - ホームセンター 都道府県別販売額等"
      - name: "0003288053"
        description: "出入国管理統計 - 国籍・地域別 入国目的別 新規入国外国人"
      - name: "0003288041"
        description: "出入国管理統計 - 港別 出入国者"
      - name: "0004026265"
        description: "人口推計 - 都道府県別 出生児数・死亡者数"
      - name: "0004026702"
        description: "住民基本台帳人口移動報告 - 移動前の住所地別転入者数"
      - name: "0003441258"
        description: "小売物価統計調査 - 都道府県別 消費者物価地域差指数（10大費目別）"
      - name: "0003195002"
        description: "犯罪統計 - 都道府県別 刑法犯 認知・検挙件数"
      - name: "0003288314"
        description: "出入国管理統計 - 船舶観光上陸許可（国籍・港別）"
