version: 2

sources:
  - name: estat
    description: "e-Stat APIから取得した統計データ（CSVファイル）"
    meta:
      external_location: "../data/{name}/{name}.csv"
    tables:
      - name: "0000010103"
        description: "社会・人口統計体系 - Ｃ 経済基盤（都道府県別）"
        columns:
          - name: "観測値_code"
            description: "観測値の分類コード。1種類: 00001"
          - name: "観測値"
            description: "観測値の分類名称。1種類: 観測値"
          - name: "Ｃ　経済基盤_code"
            description: "経済基盤指標の分類コード。548種類"
          - name: "Ｃ　経済基盤"
            description: "経済基盤指標の名称。548種類"
          - name: "地域_code"
            description: "都道府県コード。48種類"
          - name: "地域"
            description: "都道府県名。48種類"
          - name: "調査年_code"
            description: "調査年コード。50種類"
          - name: "調査年"
            description: "調査年の表示名称。50種類"
          - name: "unit"
            description: "値の単位。31種類"
          - name: "value"
            description: "指標の数値。188875種類"
      - name: "0000010112"
        description: "社会・人口統計体系 - Ｌ 家計（都道府県別）"
        columns:
          - name: "観測値_code"
            description: "観測値の分類コード。1種類: 00001"
          - name: "観測値"
            description: "観測値の分類名称。1種類: 観測値"
          - name: "Ｌ　家計_code"
            description: "家計指標の分類コード。265種類"
          - name: "Ｌ　家計"
            description: "家計指標の名称。265種類"
          - name: "地域_code"
            description: "都道府県コード。48種類"
          - name: "地域"
            description: "都道府県名。48種類"
          - name: "調査年_code"
            description: "調査年コード。50種類"
          - name: "調査年"
            description: "調査年の表示名称。50種類"
          - name: "unit"
            description: "値の単位。9種類"
          - name: "value"
            description: "指標の数値。85866種類"
      - name: "0002210008"
        description: "家計調査 - 貯蓄・負債（都市階級・地方・県庁所在市別）"
        columns:
          - name: "表章項目_code"
            description: "表章項目コード。1種類: 01"
          - name: "表章項目"
            description: "表章項目名称。1種類: 金額"
          - name: "貯蓄・負債_code"
            description: "貯蓄・負債の分類コード。42種類"
          - name: "貯蓄・負債"
            description: "貯蓄・負債の分類名称。42種類"
          - name: "世帯区分_code"
            description: "世帯区分コード。4種類: 01, 02, 03, 04"
          - name: "世帯区分"
            description: "世帯区分の名称。4種類: 二人以上の世帯のうち勤労者世帯（2000年～）, 二人以上の世帯のうち勤労者世帯（農林漁家世帯を除く）（1985年～2007年,2017年）, 二人以上の世帯（2000年～）, 二人以上の世帯（農林漁家世帯を除く）（1985年～2007年,2017年）"
          - name: "地域区分_code"
            description: "地域区分コード。75種類"
          - name: "地域区分"
            description: "地域区分の名称。75種類"
          - name: "時間軸（年次）_code"
            description: "年次コード。23種類"
          - name: "時間軸（年次）"
            description: "年次の表示名称。23種類"
          - name: "unit"
            description: "値の単位。7種類"
          - name: "value"
            description: "指標の数値。6186種類"
      - name: "0004026264"
        description: "人口推計 - 都道府県・男女別人口"
        columns:
          - name: "表章項目_code"
            description: "表章項目コード。1種類: 008"
          - name: "表章項目"
            description: "表章項目名称。1種類: 人口"
          - name: "人口及び人口増減_code"
            description: "人口及び人口増減の分類コード。5種類: 204, 207, 211, 212, 213"
          - name: "人口及び人口増減"
            description: "人口及び人口増減の分類名称。5種類: 人口, 国籍の異動による純増減, 増減の計, 社会増減, 自然増減"
          - name: "男女別_code"
            description: "男女別コード。3種類: 000, 001, 002"
          - name: "男女別"
            description: "男女別の名称。3種類: 女, 男, 男女計"
          - name: "人口_code"
            description: "人口区分コード。2種類: 001, 002"
          - name: "人口"
            description: "人口区分の名称。2種類: 日本人人口, 総人口"
          - name: "全国・都道府県_code"
            description: "全国・都道府県コード。48種類"
          - name: "全国・都道府県"
            description: "全国・都道府県名。48種類"
          - name: "時間軸（年間）_code"
            description: "年次コード。3種類: 2023001001, 2023001011, 2024001001"
          - name: "時間軸（年間）"
            description: "年次の表示名称。3種類: 2023年10月1日現在, 2023年10月～2024年9月, 2024年10月1日現在"
          - name: "unit"
            description: "値の単位。1種類: 人"
          - name: "value"
            description: "指標の数値。1510種類"
      - name: "0004032502"
        description: "商業動態統計調査 - コンビニエンスストア 都道府県別販売額等"
        columns:
          - name: "単位_db_code"
            description: "単位コード。2種類: 0101300, 0105200"
          - name: "単位_db"
            description: "単位の名称。2種類: 店, 百万円"
          - name: "表頭_集計項目_db_code"
            description: "表頭集計項目コード。2種類: 01040100, 01040200"
          - name: "表頭_集計項目_db"
            description: "表頭集計項目の名称。2種類: 店舗数, 販売額"
          - name: "表側_集計項目_db_code"
            description: "表側集計項目コード。2種類: 01030100, 01030200"
          - name: "表側_集計項目_db"
            description: "表側集計項目の名称。2種類: 増減率(%), 販売額等"
          - name: "都道府県_code"
            description: "都道府県コード。47種類"
          - name: "都道府県"
            description: "都道府県名。47種類"
          - name: "時間軸_db_code"
            description: "時間軸コード。26種類"
          - name: "時間軸_db"
            description: "時間軸の表示名称。26種類"
          - name: "unit"
            description: "値の単位（CSVの元カラム）。1種類: "
          - name: "value"
            description: "指標の数値。1741種類"
      - name: "0004032505"
        description: "商業動態統計調査 - 家電大型専門店 都道府県別販売額等"
        columns:
          - name: "単位_db_code"
            description: "単位コード。2種類: 0101300, 0105200"
          - name: "単位_db"
            description: "単位の名称。2種類: 店, 百万円"
          - name: "表頭_集計項目_db_code"
            description: "表頭集計項目コード。2種類: 01040110, 01040200"
          - name: "表頭_集計項目_db"
            description: "表頭集計項目の名称。2種類: 店舗数, 販売額等"
          - name: "表側_集計項目_db_code"
            description: "表側集計項目コード。2種類: 01030100, 01030200"
          - name: "表側_集計項目_db"
            description: "表側集計項目の名称。2種類: 増減率(%), 販売額等"
          - name: "都道府県_code"
            description: "都道府県コード。47種類"
          - name: "都道府県"
            description: "都道府県名。47種類"
          - name: "時間軸_db_code"
            description: "時間軸コード。26種類"
          - name: "時間軸_db"
            description: "時間軸の表示名称。26種類"
          - name: "unit"
            description: "値の単位（CSVの元カラム）。1種類: "
          - name: "value"
            description: "指標の数値。1458種類"
      - name: "0004032508"
        description: "商業動態統計調査 - ドラッグストア 都道府県別販売額等"
        columns:
          - name: "単位_db_code"
            description: "単位コード。2種類: 0101300, 0105200"
          - name: "単位_db"
            description: "単位の名称。2種類: 店, 百万円"
          - name: "表頭_集計項目_db_code"
            description: "表頭集計項目コード。2種類: 01040110, 01040200"
          - name: "表頭_集計項目_db"
            description: "表頭集計項目の名称。2種類: 店舗数, 販売額等"
          - name: "表側_集計項目_db_code"
            description: "表側集計項目コード。2種類: 01030100, 01030200"
          - name: "表側_集計項目_db"
            description: "表側集計項目の名称。2種類: 増減率(%), 販売額等"
          - name: "都道府県_code"
            description: "都道府県コード。47種類"
          - name: "都道府県"
            description: "都道府県名。47種類"
          - name: "時間軸_db_code"
            description: "時間軸コード。26種類"
          - name: "時間軸_db"
            description: "時間軸の表示名称。26種類"
          - name: "unit"
            description: "値の単位（CSVの元カラム）。1種類: "
          - name: "value"
            description: "指標の数値。1777種類"
      - name: "0004032511"
        description: "商業動態統計調査 - ホームセンター 都道府県別販売額等"
        columns:
          - name: "単位_db_code"
            description: "単位コード。2種類: 0101300, 0105200"
          - name: "単位_db"
            description: "単位の名称。2種類: 店, 百万円"
          - name: "表頭_集計項目_db_code"
            description: "表頭集計項目コード。2種類: 01040110, 01040200"
          - name: "表頭_集計項目_db"
            description: "表頭集計項目の名称。2種類: 店舗数, 販売額等"
          - name: "表側_集計項目_db_code"
            description: "表側集計項目コード。2種類: 01030100, 01030200"
          - name: "表側_集計項目_db"
            description: "表側集計項目の名称。2種類: 増減率(%), 販売額等"
          - name: "都道府県_code"
            description: "都道府県コード。47種類"
          - name: "都道府県"
            description: "都道府県名。47種類"
          - name: "時間軸_db_code"
            description: "時間軸コード。26種類"
          - name: "時間軸_db"
            description: "時間軸の表示名称。26種類"
          - name: "unit"
            description: "値の単位（CSVの元カラム）。1種類: "
          - name: "value"
            description: "指標の数値。1471種類"
      - name: "0003288053"
        description: "出入国管理統計 - 国籍・地域別 入国目的別 新規入国外国人"
        columns:
          - name: "表章項目_code"
            description: "表章項目コード。1種類: 100"
          - name: "表章項目"
            description: "表章項目名称。1種類: 入国外国人"
          - name: "入国目的_code"
            description: "入国目的コード。51種類"
          - name: "入国目的"
            description: "入国目的の名称。51種類"
          - name: "国籍・地域_code"
            description: "国籍・地域コード。210種類"
          - name: "国籍・地域"
            description: "国籍・地域の名称。210種類"
          - name: "時間軸(年次)_code"
            description: "年次コード。23種類"
          - name: "時間軸(年次)"
            description: "年次の表示名称。23種類"
          - name: "unit"
            description: "値の単位。1種類: 人"
          - name: "value"
            description: "指標の数値。5903種類"
      - name: "0003288041"
        description: "出入国管理統計 - 港別 出入国者"
        columns:
          - name: "表章項目_code"
            description: "表章項目コード。1種類: 140"
          - name: "表章項目"
            description: "表章項目名称。1種類: 出入国者"
          - name: "出入国者_code"
            description: "出入国者区分コード。4種類: 100, 110, 120, 130"
          - name: "出入国者"
            description: "出入国者区分の名称。4種類: 協定該当者, 外国人, 日本人, 計"
          - name: "入国・出国_code"
            description: "入国・出国の方向コード。3種類: 100, 110, 120"
          - name: "入国・出国"
            description: "入国・出国の方向名称。3種類: 入国者, 出国者, 総数"
          - name: "港_code"
            description: "港コード。352種類"
          - name: "港"
            description: "港の名称。352種類"
          - name: "時間軸(年次)_code"
            description: "年次コード。28種類"
          - name: "時間軸(年次)"
            description: "年次の表示名称。28種類"
          - name: "unit"
            description: "値の単位。1種類: 人"
          - name: "value"
            description: "指標の数値。7425種類"
      - name: "0004026265"
        description: "人口推計 - 都道府県別 出生児数・死亡者数"
        columns:
          - name: "表章項目_code"
            description: "表章項目コード。1種類: 012"
          - name: "表章項目"
            description: "表章項目名称。1種類: 出生児数・死亡者数"
          - name: "出生児数・死亡者数_code"
            description: "出生児数・死亡者数の分類コード。2種類: 001, 002"
          - name: "出生児数・死亡者数"
            description: "出生児数・死亡者数の分類名称。2種類: 出生児数, 死亡者数"
          - name: "男女別_code"
            description: "男女別コード。3種類: 000, 001, 002"
          - name: "男女別"
            description: "男女別の名称。3種類: 女, 男, 男女計"
          - name: "日本人・外国人_code"
            description: "日本人・外国人の区分コード。2種類: 001, 002"
          - name: "日本人・外国人"
            description: "日本人・外国人の区分名称。2種類: 外国人, 日本人"
          - name: "全国・都道府県_code"
            description: "全国・都道府県コード。48種類"
          - name: "全国・都道府県"
            description: "全国・都道府県名。48種類"
          - name: "時間軸（年間）_code"
            description: "年次コード。1種類: 2023001011"
          - name: "時間軸（年間）"
            description: "年次の表示名称。1種類: 2023年10月～2024年9月"
          - name: "unit"
            description: "値の単位。1種類: 人"
          - name: "value"
            description: "指標の数値。454種類"
      - name: "0004026702"
        description: "住民基本台帳人口移動報告 - 移動前の住所地別転入者数"
        columns:
          - name: "表章項目_code"
            description: "表章項目コード。1種類: 18"
          - name: "表章項目"
            description: "表章項目名称。1種類: 移動前の住所地別転入者数"
          - name: "移動後の住所地（現住地）2020～_code"
            description: "移動後の住所地コード。1960種類"
          - name: "移動後の住所地（現住地）2020～"
            description: "移動後の住所地名称。1866種類"
          - name: "国籍_code"
            description: "国籍コード。3種類: 60000, 61000, 62000"
          - name: "国籍"
            description: "国籍の名称。3種類: 外国人移動者, 日本人移動者, 移動者"
          - name: "移動前の住所地（前住地）2020～_code"
            description: "移動前の住所地コード。1832種類"
          - name: "移動前の住所地（前住地）2020～"
            description: "移動前の住所地名称。1681種類"
          - name: "時間軸_code"
            description: "年次コード。1種類: 2024000000"
          - name: "時間軸"
            description: "年次の表示名称。1種類: 2024年"
          - name: "unit"
            description: "値の単位。1種類: 人"
          - name: "value"
            description: "指標の数値。5778種類"
      - name: "0003441258"
        description: "小売物価統計調査 - 都道府県別 消費者物価地域差指数（10大費目別）"
        columns:
          - name: "表章項目_code"
            description: "表章項目コード。1種類: 40"
          - name: "表章項目"
            description: "表章項目名称。1種類: 指数"
          - name: "10大費目_code"
            description: "10大費目コード。12種類"
          - name: "10大費目"
            description: "10大費目の名称。12種類"
          - name: "地域_code"
            description: "地域コード。110種類"
          - name: "地域"
            description: "地域名。110種類"
          - name: "時間軸(年)_code"
            description: "年次コード。12種類"
          - name: "時間軸(年)"
            description: "年次の表示名称。12種類"
          - name: "unit"
            description: "値の単位。1種類: "
          - name: "value"
            description: "指標の数値。383種類"
      - name: "0003195002"
        description: "犯罪統計 - 都道府県別 刑法犯 認知・検挙件数"
        columns:
          - name: "認知・検挙件数・検挙人員_code"
            description: "認知・検挙件数・検挙人員の分類コード。4種類: 100, 110, 120, 130"
          - name: "認知・検挙件数・検挙人員"
            description: "認知・検挙件数・検挙人員の分類名称。4種類: 検挙人員, 検挙件数, 検挙率, 認知件数"
          - name: "管区警察局_code"
            description: "管区警察局コード。60種類"
          - name: "管区警察局"
            description: "管区警察局の名称。60種類"
          - name: "時間軸(年次)_code"
            description: "年次コード。11種類"
          - name: "時間軸(年次)"
            description: "年次の表示名称。11種類"
          - name: "unit"
            description: "値の単位。3種類: %, 人, 件"
          - name: "value"
            description: "指標の数値。2190種類"
      - name: "0003288314"
        description: "出入国管理統計 - 船舶観光上陸許可（国籍・港別）"
        columns:
          - name: "表章項目_code"
            description: "表章項目コード。1種類: 420"
          - name: "表章項目"
            description: "表章項目名称。1種類: 船舶観光上陸許可を受けた外国人"
          - name: "国籍・地域_code"
            description: "国籍・地域コード。177種類"
          - name: "国籍・地域"
            description: "国籍・地域の名称。177種類"
          - name: "港_code"
            description: "港コード。34種類"
          - name: "港"
            description: "港の名称。34種類"
          - name: "時間軸(年次)_code"
            description: "年次コード。9種類"
          - name: "時間軸(年次)"
            description: "年次の表示名称。9種類"
          - name: "unit"
            description: "値の単位。1種類: 人"
          - name: "value"
            description: "指標の数値。1231種類"
